name: thitracnghiemapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cached_network_image: ^3.4.1
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_secure_storage: ^9.2.4
  google_sign_in: ^6.2.1
  http: ^1.5.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  json_serializable: ^6.11.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app_icon.png
  adaptive_icon_background: "#FFFFFF"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: assets/app_icon.png
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: assets/app_icon.png
    icon_size: 48
  macos:
    generate: true
    image_path: assets/app_icon.png

flutter:
  uses-material-design: true
  assets:
    - .env
